definitions:
  datasets:
    d1:
      format: Generic
      params:
        path: LSTM_dataset/sequences_under_30.tsv
        is_repertoire: False
        paired: False
        region_type: FULL_SEQUENCE
  encodings:
    cti: CharToInt
    one_hot: OneHot
  ml_methods:
    PWM: PWM
    LSTM_1:
      LSTM:
        batch_size: 64
        rnn_units: 1024
        embedding_dim: 256
        epochs: 20
    LSTM_2:
      LSTM:
        batch_size: 8
        rnn_units: 128
        embedding_dim: 32
        epochs: 5
  reports:
    PWM_report: GeneratorReport
    LSTM_report: GeneratorReportLSTM
instructions:
  generative_instruction:
    type: GenerativeModel
    generators:
      PWM:
        dataset: d1
        encoding: one_hot
        ml_method: PWM
        report: PWM_report
        amount: 20000
      LSTM_1:
        dataset: d1
        encoding: cti
        ml_method: LSTM_1
        report: LSTM_report
        amount: 20000
      LSTM_2:
        dataset: d1
        encoding: cti
        ml_method: LSTM_2
        report: LSTM_report
        amount: 20000


