definitions:
  datasets:
    d1:
      format: Generic
      params:
        path: LSTM_dataset/sequences_under_30.tsv
        is_repertoire: False
        paired: False
        region_type: FULL_SEQUENCE
  encodings:
    e1: CharToInt
  ml_methods:
    G1:
      LSTM:
        batch_size: 8
        rnn_units: 128
        embedding_dim: 32
        epochs: 5
  reports:
    GeneratorReport: GeneratorReportLSTM
instructions:
  machine_learning_instruction:
    type: GenerativeModel
    generators:
      generator_1:
        dataset: d1
        encoding: e1
        ml_method: G1
        report: GeneratorReport
        amount: 20000


