definitions:
  datasets:
    d1:
      format: Generic
      params:
        path: datasets/sequences_under_30.tsv
        is_repertoire: False
        paired: False
        region_type: FULL_SEQUENCE
  encodings:
    e1: OneHot
  ml_methods:
    G1:
      VAE:
        cores_for_training: 8
        layers: 2
        epochs: 2
        latent_dim: 2
        batch_size: 64
  reports:
    GeneratorReport: GeneratorReport
instructions:
  machine_learning_instruction:
    type: GenerativeModel
    generators:
      generator_1:
        dataset: d1
        encoding: e1
        ml_method: G1
        report: GeneratorReport


