training_set_identifier_path: null
training_percentage: 0.7
max_positions: 4
min_precision: 0
min_recall: 0
min_true_positives: 1
highlight_motifs_name: Highlighted motif
min_points_in_window: 50
smoothing_constant1: 5
smoothing_constant2: 10
plot_smoothed_combined_precision: True